trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: credentials
  - name: NODEVER
    value: 14.x

stages:
  - stage: UnitTests
    displayName: Run unit tests
    jobs:
      - job: unitTests
        displayName: "Base build and unit tests"
        strategy:
          matrix:
            Node14:
              NODEVER: 14.x
            Node16:
              NODEVER: 16.x
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: |
              ./scripts/check-package-names.sh
            displayName: "Check correct usage of Caliper package names"
          - script: |
              npm install
              npm run bootstrap
            displayName: "Install project dependencies"
          - script: |
              ./packages/caliper-publish/publish.js version check
            displayName: "Check the version consistency of subpackages"
          - script: |
              npm test
            displayName: "Run unit tests"

  - stage: IntegrationTests
    displayName: Run integration tests
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    dependsOn: UnitTests
    jobs:
      - job: fabricIntegration
        displayName: "Fabric Integration Test"
        strategy:
          matrix:
            Node14:
              NODEVER: 14.x
            Node16:
              NODEVER: 16.x
        variables: { BENCHMARK: fabric }
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: |
              .build/benchmark-integration-test-direct.sh

      - job: ethereumIntegration
        displayName: "Ethereum Integration Test"
        strategy:
          matrix:
            Node14:
              NODEVER: 14.x
            Node16:
              NODEVER: 16.x
        variables: { BENCHMARK: ethereum }
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: |
              .build/benchmark-integration-test-direct.sh

      - job: besuIntegration
        displayName: "Besu Integration Test"
        strategy:
          matrix:
            Node14:
              NODEVER: 14.x
            Node16:
              NODEVER: 16.x
        variables: { BENCHMARK: besu }
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: |
              .build/benchmark-integration-test-direct.sh

      - job: fiscoIntegration
        displayName: "FISCO BCOS Integration Test"
        strategy:
          matrix:
            Node14:
              NODEVER: 14.x
            Node16:
              NODEVER: 16.x
        variables: { BENCHMARK: fisco-bcos }
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: |
              .build/benchmark-integration-test-direct.sh

      - job: generatorIntegration
        displayName: "Generator Integration Test"
        strategy:
          matrix:
            Node14:
              NODEVER: 14.x
            Node16:
              NODEVER: 16.x
        variables: { BENCHMARK: generator }
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: |
              .build/benchmark-integration-test-direct.sh

  - stage: Publish
    displayName: Publish Caliper
    # having a blind succeeded here will not work if a preceding stage was skipped
    condition: and(not(failed('UnitTests')), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - job: PublishCaliper
        displayName: "Publish Caliper to NPM and DockerHub"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "$(NODEVER)"
            displayName: "Install Node.js"
          - script: .build/publish-caliper.sh
            displayName: Publish Caliper
            env:
              NPM_TOKEN: "$(npm)"
              DOCKER_USER: "$(DockerHub-Username)"
              DOCKER_TOKEN: "$(DockerHub-Password)"
