blank_issues_enabled: true
contact_links:
  - name: Hyperledger Discord
    url: https://discord.com/channels/905194001349627914/941417677778473031
    about: Please ask general questions about the project in the Caliper channel (Discord id required).
  - name: Hyperledger Caliper mailing list
    url: https://lists.hyperledger.org/g/caliper
    about: Please ask general questions about the project here (LFID recommended).